services:
  db:
    image: postgres:15-alpine
    container_name: mosentiliztli-postgres
    environment:
      POSTGRES_DB: mosentiliztli
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    container_name: mosentiliztli-backend
    ports:
      - "8085:8080" # El puerto 8085 es el de tu VPS, 8080 es el interno de Spring Boot
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mosentiliztli
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
